# frozen_string_literal: true

# Runs Autoprefixer over the CSS generated by Jekyll's Sass pipeline,
# so the output matches the official compiled Bootstrap builds
# (see https://getbootstrap.com/docs/5.3/getting-started/download/#source-files).
# Requires the autoprefixer-rails gem and a JS runtime (e.g. Node).

require "autoprefixer-rails"

# Bootstrap's official browser support targets,
# https://github.com/twbs/bootstrap/blob/main/.browserslistrc
AUTOPREFIXER_BROWSERS = [
  ">= 0.5%",
  "last 2 major versions",
  "not dead",
  "Chrome >= 60",
  "Firefox >= 60",
  "Firefox ESR",
  "iOS >= 12",
  "Safari >= 12",
  "not Explorer <= 11"
].freeze

Jekyll::Hooks.register :site, :post_write do |site|
  Dir.glob(File.join(site.dest, "assets", "css", "**", "*.css")).each do |file|
    css = File.read(file)
    map_file = "#{file}.map"
    # If the Sass converter wrote a source map, pass it through Autoprefixer so
    # the map stays accurate and the sourceMappingURL comment is preserved.
    map_opts = if File.exist?(map_file)
                 { prev: File.read(map_file), inline: false, annotation: File.basename(map_file) }
               else
                 false
               end
    result = AutoprefixerRails.process(
      css,
      overrideBrowserslist: AUTOPREFIXER_BROWSERS,
      from: File.basename(file),
      to: File.basename(file),
      map: map_opts
    )
    File.write(file, result.css) unless result.css == css
    File.write(map_file, result.map) if map_opts && result.map
  end
end
