# frozen_string_literal: true

# Runs Autoprefixer over the CSS generated by Jekyll's Sass pipeline,
# so the output matches the official compiled Bootstrap builds
# (see https://getbootstrap.com/docs/5.3/getting-started/download/#source-files).
# Requires the autoprefixer-rails gem and a JS runtime (e.g. Node).

require "autoprefixer-rails"

# Bootstrap's official browser support targets,
# https://github.com/twbs/bootstrap/blob/main/.browserslistrc
AUTOPREFIXER_BROWSERS = [
  ">= 0.5%",
  "last 2 major versions",
  "not dead",
  "Chrome >= 60",
  "Firefox >= 60",
  "Firefox ESR",
  "iOS >= 12",
  "Safari >= 12",
  "not Explorer <= 11"
].freeze

Jekyll::Hooks.register :site, :post_write do |site|
  Dir.glob(File.join(site.dest, "assets", "css", "**", "*.css")).each do |file|
    css = File.read(file)
    prefixed = AutoprefixerRails.process(
      css,
      overrideBrowserslist: AUTOPREFIXER_BROWSERS,
      map: false
    ).css
    File.write(file, prefixed) unless prefixed == css
  end
end
